services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8305}:8761

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: db_user
      HS_POSTGRES_USERNAME: hs
      HS_POSTGRES_PASSWORD: example
    ports:
      - ${HS_USERS_POSTGRES_PORT:-8302}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_user"]
      start_period: 60s
      interval: 10s
      timeout: 60s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: example
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_user
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.user.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

  users:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      liquibase:
        condition: service_completed_successfully
    ports:
      - ${HS_USER_PORT:-8300}:8763
    environment:
      HS_USER_EUREKA_URI: http://eureka:8761/eureka
      HS_USER_DATASOURCE_HOST: postgres
      HS_USER_DATASOURCE_PORT: 5432
      HS_USER_DATASOURCE_DATABASE: db_user
      HS_USER_DATASOURCE_USERNAME: hs
      HS_USER_DATASOURCE_PASSWORD: example
      HS_USER_JWT_SECRET_KEY: H3G7wpVdJNA9hsK4zaQm6uCUZqHLg2RFKs7D8M6J9mbf
      HS_USER_JWT_EXPIRATION: 86400000

volumes:
  postgres-data:
