services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8761}:8761

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: db_user
      HS_POSTGRES_USERNAME: ${HS_POSTGRES_USERNAME}
      HS_POSTGRES_PASSWORD: ${HS_POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/

  liquibase:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      - postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_POSTGRES_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_user
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.user.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

  users:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_USER_PORT:-8763}:8763
    environment:
      HS_USER_EUREKA_URI: http://eureka:8761/eureka
      HS_USER_DATASOURCE_HOST: postgres
      HS_USER_DATASOURCE_PORT: 5432
      HS_USER_DATASOURCE_DATABASE: db_user
      HS_USER_DATASOURCE_USERNAME: ${HS_POSTGRES_USERNAME}
      HS_USER_DATASOURCE_PASSWORD: ${HS_POSTGRES_PASSWORD}
      HS_USER_JWT_EXPIRATION: 3600000
      HS_USER_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645

volumes:
  postgres-data:
