#!/bin/env bash

set -e

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
	CREATE DATABASE $POSTGRES_DATABASE;
  CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DATABASE TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "$POSTGRES_DATABASE" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO $POSTGRES_USER;
EOSQL
