name: Development + Staging (PR)

on:
  push:

jobs:
  namer:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch_name.outputs.branch }}
      tag: ${{ steps.branch_name.outputs.tag }}

    steps:
      - name: Get tag & branch name
        id: branch_name
        run: |-
          branch=${{ github.ref_name }}
          echo "branch=${branch}"
          echo "branch=${branch}" >> $GITHUB_OUTPUT

          tag="${branch////-}"
          echo "tag=${tag}"
          echo "tag=${tag}" >> $GITHUB_OUTPUT

  build:
    needs:
      - namer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: jdk
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Build and push
        uses: niqzart/ffs-devops/docker-build@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.event.repository.name }}
          tag: ${{ github.ref_name == 'main' && needs.namer.outputs.tag || 'latest' }}
          base-tag: latest
          dockerfile: "./dockerfile"
